name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  setup:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

  checks:
    runs-on: ubuntu-24.04
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Run checks
        run: ./gradlew ktfmtCheckMain check

#      - name: Upload test results
#        uses: actions/upload-artifact@v4
#        with:
#          name: test-results
#          path: build/reports/
#          retention-days: 5
#          overwrite: 'true'

  build:
    needs: [setup, checks]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: ./gradlew build shadowJar
